[package]
name = "snl-semantic"
version = "0.1.0"
authors = ["Yesterday17 <t@yesterday17.cn>"]
edition = "2018"

[dependencies]
snl-rdp = { path = "../snl-rdp" }
snl-utils = { path = "../snl-utils" }
